export const LGA_ZONE_MAP: Record<string, string> = {
  // Abuja (FCT)
  "abuja (fct)_bwari": "FCT North",
  "abuja (fct)_bwari area council": "FCT North",
  "abuja (fct)_gwagwalada": "FCT North",
  "abuja (fct)_gwagwalada area council": "FCT North",
  "abuja (fct)_kuje": "FCT North",
  "abuja (fct)_kuje area council": "FCT North",
  "abuja (fct)_municipal area council (amac)": "FCT Central",
  "abuja (fct)_municipal area council": "FCT Central",
  "abuja (fct)_amac": "FCT Central",
  "abuja (fct)_abaji": "FCT South",
  "abuja (fct)_abaji area council": "FCT South",
  "abuja (fct)_kwali": "FCT South",
  "abuja (fct)_kwali area council": "FCT South",

  // Oyo
  "oyo_afijio": "Oyo North",
  "oyo_atiba": "Oyo North",
  "oyo_atisbo": "Oyo North",
  "oyo_iwajowa": "Oyo North",
  "oyo_kajola": "Oyo North",
  "oyo_ogo oluwa": "Oyo North",
  "oyo_orelope": "Oyo North",
  "oyo_ori ire": "Oyo North",
  "oyo_oyo east": "Oyo North",
  "oyo_oyo west": "Oyo North",
  "oyo_saki east": "Oyo North",
  "oyo_saki west": "Oyo North",
  "oyo_surulere": "Oyo North",
  "oyo_egbeda": "Oyo Central",
  "oyo_ibadan north": "Oyo Central",
  "oyo_ibadan north east": "Oyo Central",
  "oyo_ibadan north-east": "Oyo Central",
  "oyo_ibadan north west": "Oyo Central",
  "oyo_ibadan north-west": "Oyo Central",
  "oyo_ibadan south east": "Oyo Central",
  "oyo_ibadan south-east": "Oyo Central",
  "oyo_ibadan south west": "Oyo Central",
  "oyo_ibadan south-west": "Oyo Central",
  "oyo_ibarapa central": "Oyo Central",
  "oyo_ibarapa east": "Oyo Central",
  "oyo_ibarapa north": "Oyo Central",
  "oyo_lagelu": "Oyo Central",
  "oyo_oluyole": "Oyo Central",
  "oyo_ona ara": "Oyo Central",
  "oyo_ona-ara": "Oyo Central",
  "oyo_akinyele": "Oyo South",
  "oyo_ido": "Oyo South",
  "oyo_ifedapo": "Oyo South",
  "oyo_iseyin": "Oyo South",
  "oyo_itesiwaju": "Oyo South",
  "oyo_iyareloju": "Oyo South",
  "oyo_ogbomosho north": "Oyo South",
  "oyo_ogbomosho-north": "Oyo South",
  "oyo_ogbomosho south": "Oyo South",
  "oyo_ogbomosho-south": "Oyo South",
  "oyo_olorunsogo": "Oyo South",

  // Kwara
  "kwara_baruten": "Kwara North",
  "kwara_edu": "Kwara North",
  "kwara_kaiama": "Kwara North",
  "kwara_moro": "Kwara North",
  "kwara_pategi": "Kwara North",
  "kwara_asa": "Kwara Central",
  "kwara_ekiti": "Kwara Central",
  "kwara_ilorin east": "Kwara Central",
  "kwara_ilorin-east": "Kwara Central",
  "kwara_ilorin south": "Kwara Central",
  "kwara_ilorin-south": "Kwara Central",
  "kwara_ilorin west": "Kwara Central",
  "kwara_ilorin-west": "Kwara Central",
  "kwara_offa": "Kwara Central",
  "kwara_oyun": "Kwara Central",
  "kwara_ifelodun": "Kwara South",
  "kwara_irepodun": "Kwara South",
  "kwara_isin": "Kwara South",
  "kwara_oke ero": "Kwara South",
  "kwara_oke-hero": "Kwara South",

  // Ogun
  "ogun_abeokuta north": "Ogun Central",
  "ogun_abeokuta-north": "Ogun Central",
  "ogun_abeokuta south": "Ogun Central",
  "ogun_abeokuta-south": "Ogun Central",
  "ogun_ewekoro": "Ogun Central",
  "ogun_ifo": "Ogun Central",
  "ogun_imeko afon": "Ogun Central",
  "ogun_imeko-afon": "Ogun Central",
  "ogun_obafemi owode": "Ogun Central",
  "ogun_obafemi-owode": "Ogun Central",
  "ogun_odeda": "Ogun Central",
  "ogun_ikenne": "Ogun East",
  "ogun_ijebu east": "Ogun East",
  "ogun_ijebu-east": "Ogun East",
  "ogun_ijebu north": "Ogun East",
  "ogun_ijebu-north": "Ogun East",
  "ogun_ijebu north east": "Ogun East",
  "ogun_ijebu-north-east": "Ogun East",
  "ogun_ijebu ode": "Ogun East",
  "ogun_ijebu-ode": "Ogun East",
  "ogun_ogun waterside": "Ogun East",
  "ogun_ogun-waterside": "Ogun East",
  "ogun_remo north": "Ogun East",
  "ogun_remo-north": "Ogun East",
  "ogun_sagamu": "Ogun East",
  "ogun_ado-odo/ota": "Ogun West",
  "ogun_ado odo ota": "Ogun West",
  "ogun_yewa north": "Ogun West",
  "ogun_yewa-north": "Ogun West",
  "ogun_yewa south": "Ogun West",
  "ogun_yewa-south": "Ogun West",
  "ogun_ipokia": "Ogun West",
  "ogun_odogbolu": "Ogun West",

  // Benue
  "benue_ado": "Benue North East",
  "benue_agatu": "Benue North East",
  "benue_apa": "Benue North East",
  "benue_buruku": "Benue North East",
  "benue_gboko": "Benue North East",
  "benue_guma": "Benue North East",
  "benue_gwer east": "Benue North East",
  "benue_gwer-east": "Benue North East",
  "benue_gwer west": "Benue North East",
  "benue_gwer-west": "Benue North East",
  "benue_katsina ala": "Benue North West",
  "benue_katsina-ala": "Benue North West",
  "benue_konshisha": "Benue North West",
  "benue_kwande": "Benue North West",
  "benue_logo": "Benue North West",
  "benue_makurdi": "Benue North West",
  "benue_tarka": "Benue North West",
  "benue_ushongo": "Benue North West",
  "benue_vandeikya": "Benue North West",
  "benue_obi": "Benue South",
  "benue_ogbadibo": "Benue South",
  "benue_ohimini": "Benue South",
  "benue_oju": "Benue South",
  "benue_okpokwu": "Benue South",
  "benue_otukpo": "Benue South",

  // Edo
  "edo_akoko-edo": "Edo North",
  "edo_akoko edo": "Edo North",
  "edo_etsako central": "Edo North",
  "edo_etsako-central": "Edo North",
  "edo_etsako east": "Edo North",
  "edo_etsako-east": "Edo North",
  "edo_etsako west": "Edo North",
  "edo_etsako-west": "Edo North",
  "edo_owan east": "Edo North",
  "edo_owan-east": "Edo North",
  "edo_owan west": "Edo North",
  "edo_owan-west": "Edo North",
  "edo_esan central": "Edo Central",
  "edo_esan-central": "Edo Central",
  "edo_esan north east": "Edo Central",
  "edo_esan-north-east": "Edo Central",
  "edo_esan south east": "Edo Central",
  "edo_esan-south-east": "Edo Central",
  "edo_esan west": "Edo Central",
  "edo_esan-west": "Edo Central",
  "edo_igueben": "Edo Central",
  "edo_egor": "Edo South",
  "edo_ikpoba okha": "Edo South",
  "edo_ikpoba-okha": "Edo South",
  "edo_orhionmwon": "Edo South",
  "edo_ovia north east": "Edo South",
  "edo_ovia-north-east": "Edo South",
  "edo_ovia south west": "Edo South",
  "edo_ovia-south-west": "Edo South",
  "edo_oredo": "Edo South",
  "edo_uhunmwonde": "Edo South",

  // Ondo
  "ondo_akoko north east": "Ondo North",
  "ondo_akoko-north-east": "Ondo North",
  "ondo_akoko north west": "Ondo North",
  "ondo_akoko-north-west": "Ondo North",
  "ondo_akoko south east": "Ondo North",
  "ondo_akoko-south-east": "Ondo North",
  "ondo_akoko south west": "Ondo North",
  "ondo_akoko-south-west": "Ondo North",
  "ondo_ifedore": "Ondo North",
  "ondo_akure north": "Ondo Central",
  "ondo_akure-north": "Ondo Central",
  "ondo_akure south": "Ondo Central",
  "ondo_akure-south": "Ondo Central",
  "ondo_idanre": "Ondo Central",
  "ondo_ile oluji/okeigbo": "Ondo Central",
  "ondo_ile oluji okeigbo": "Ondo Central",
  "ondo_ondo east": "Ondo Central",
  "ondo_ondo-east": "Ondo Central",
  "ondo_ondo west": "Ondo Central",
  "ondo_ondo-west": "Ondo Central",
  "ondo_ese-odo": "Ondo South",
  "ondo_ese odo": "Ondo South",
  "ondo_ilaje": "Ondo South",
  "ondo_irele": "Ondo South",
  "ondo_odigbo": "Ondo South",
  "ondo_okitipupa": "Ondo South",

  // Kano
  "kano_dala": "Kano Central",
  "kano_fagge": "Kano Central",
  "kano_gwale": "Kano Central",
  "kano_kano municipal": "Kano Central",
  "kano_nassarawa": "Kano Central",
  "kano_tarauni": "Kano Central",
  "kano_ungogo": "Kano Central",
  "kano_bagwai": "Kano North",
  "kano_bebeji": "Kano North",
  "kano_bichi": "Kano North",
  "kano_dambatta": "Kano North",
  "kano_gaya": "Kano North",
  "kano_gezawa": "Kano North",
  "kano_garun mallam": "Kano North",
  "kano_kabo": "Kano North",
  "kano_karaye": "Kano North",
  "kano_kibiya": "Kano North",
  "kano_kiru": "Kano North",
  "kano_madobi": "Kano North",
  "kano_makoda": "Kano North",
  "kano_minjibir": "Kano North",
  "kano_shanono": "Kano North",
  "kano_tofa": "Kano North",
  "kano_tsanyawa": "Kano North",
  "kano_rano": "Kano North",
  "kano_warawa": "Kano North",
  "kano_wudil": "Kano North",
  "kano_albasu": "Kano South",
  "kano_ajingi": "Kano South",
  "kano_bunkure": "Kano South",
  "kano_dawaki kudu": "Kano South",
  "kano_dawaki tofa": "Kano South",
  "kano_doguwa": "Kano South",
  "kano_garko": "Kano South",
  "kano_gwarzo": "Kano South",
  "kano_kura": "Kano South",
  "kano_kudan": "Kano South",
  "kano_rimin gado": "Kano South",
  "kano_rogo": "Kano South",
  "kano_sumaila": "Kano South",
  "kano_takai": "Kano South",
  "kano_tudun wada": "Kano South",

  // Kaduna
  "kaduna_birnin gwari": "Kaduna North",
  "kaduna_chikun": "Kaduna North",
  "kaduna_giwa": "Kaduna North",
  "kaduna_igabi": "Kaduna North",
  "kaduna_ikara": "Kaduna North",
  "kaduna_kubau": "Kaduna North",
  "kaduna_kudan": "Kaduna North",
  "kaduna_lere": "Kaduna North",
  "kaduna_makarfi": "Kaduna North",
  "kaduna_sabon gari": "Kaduna North",
  "kaduna_soba": "Kaduna North",
  "kaduna_zaria": "Kaduna North",
  "kaduna_kaduna north lga": "Kaduna Central",
  "kaduna_kaduna south lga": "Kaduna Central",
  "kaduna_kajuru": "Kaduna Central",
  "kaduna_kauru": "Kaduna Central",
  "kaduna_jaba": "Kaduna South",
  "kaduna_jema'a": "Kaduna South",
  "kaduna_jemaa": "Kaduna South",
  "kaduna_kachia": "Kaduna South",
  "kaduna_kagarko": "Kaduna South",
  "kaduna_kaura": "Kaduna South",
  "kaduna_sanga": "Kaduna South",
  "kaduna_zangon kataf": "Kaduna South",

  // Adamawa
  "adamawa_fufore": "Adamawa North",
  "adamawa_ganye": "Adamawa North",
  "adamawa_guyuk": "Adamawa North",
  "adamawa_hong": "Adamawa North",
  "adamawa_lamurde": "Adamawa North",
  "adamawa_madagali": "Adamawa North",
  "adamawa_maiha": "Adamawa North",
  "adamawa_michika": "Adamawa North",
  "adamawa_mubi north": "Adamawa North",
  "adamawa_mubi south": "Adamawa North",
  "adamawa_song": "Adamawa North",
  "adamawa_demsa": "Adamawa Central",
  "adamawa_girei": "Adamawa Central",
  "adamawa_gombi": "Adamawa Central",
  "adamawa_mayo-belwa": "Adamawa Central",
  "adamawa_numan": "Adamawa Central",
  "adamawa_shelleng": "Adamawa Central",
  "adamawa_yola north": "Adamawa Central",
  "adamawa_jada": "Adamawa South",
  "adamawa_toungo": "Adamawa South",
  "adamawa_yola south": "Adamawa South",

  // Bauchi
  "bauchi_alkaleri": "Bauchi North",
  "bauchi_bauchi": "Bauchi North",
  "bauchi_dass": "Bauchi North",
  "bauchi_gamawa": "Bauchi North",
  "bauchi_ganjuwa": "Bauchi North",
  "bauchi_giade": "Bauchi North",
  "bauchi_itas/gadau": "Bauchi North",
  "bauchi_jama'are": "Bauchi North",
  "bauchi_katagum": "Bauchi Central",
  "bauchi_kirfi": "Bauchi Central",
  "bauchi_misau": "Bauchi Central",
  "bauchi_ningi": "Bauchi Central",
  "bauchi_shira": "Bauchi Central",
  "bauchi_tafawa balewa": "Bauchi Central",
  "bauchi_warji": "Bauchi Central",
  "bauchi_bogoro": "Bauchi South",
  "bauchi_darazo": "Bauchi South",
  "bauchi_dambam": "Bauchi South",
  "bauchi_toro": "Bauchi South",
  "bauchi_zaki": "Bauchi South",

  // Borno
  "borno_abadam": "Borno North",
  "borno_bama": "Borno North",
  "borno_dikwa": "Borno North",
  "borno_gubio": "Borno North",
  "borno_guzamala": "Borno North",
  "borno_kala/balge": "Borno North",
  "borno_kukawa": "Borno North",
  "borno_mafa": "Borno North",
  "borno_monguno": "Borno North",
  "borno_ngala": "Borno North",
  "borno_nganzai": "Borno North",
  "borno_biu": "Borno Central",
  "borno_chibok": "Borno Central",
  "borno_damboa": "Borno Central",
  "borno_gwoza": "Borno Central",
  "borno_hawul": "Borno Central",
  "borno_jere": "Borno Central",
  "borno_konduga": "Borno Central",
  "borno_maiduguri": "Borno Central",
  "borno_shani": "Borno Central",
  "borno_askira/uba": "Borno South",
  "borno_kaga": "Borno South",
  "borno_kwaya kusar": "Borno South",
  "borno_marte": "Borno South",
  "borno_mobbar": "Borno South",

  // Gombe
  "gombe_akko": "Gombe North",
  "gombe_balanga": "Gombe North",
  "gombe_billiri": "Gombe North",
  "gombe_dukku": "Gombe North",
  "gombe_funakaye": "Gombe North",
  "gombe_gombe": "Gombe Central",
  "gombe_kwami": "Gombe Central",
  "gombe_nafada": "Gombe Central",
  "gombe_yamaltu/deba": "Gombe Central",
  "gombe_kaltungo": "Gombe South",
  "gombe_shomgom": "Gombe South",

  // Jigawa
  "jigawa_auyo": "Jigawa North East",
  "jigawa_biriniwa": "Jigawa North East",
  "jigawa_dutse": "Jigawa North East",
  "jigawa_guri": "Jigawa North East",
  "jigawa_gwaram": "Jigawa North East",
  "jigawa_hadejia": "Jigawa North East",
  "jigawa_kaugama": "Jigawa North East",
  "jigawa_kiri kasama": "Jigawa North East",
  "jigawa_birnin kudu": "Jigawa North West",
  "jigawa_buji": "Jigawa North West",
  "jigawa_gagarawa": "Jigawa North West",
  "jigawa_garki": "Jigawa North West",
  "jigawa_gumel": "Jigawa North West",
  "jigawa_gwiwa": "Jigawa North West",
  "jigawa_kazaure": "Jigawa North West",
  "jigawa_maigatari": "Jigawa North West",
  "jigawa_malam madori": "Jigawa North West",
  "jigawa_miga": "Jigawa North West",
  "jigawa_ringim": "Jigawa North West",
  "jigawa_babura": "Jigawa South",
  "jigawa_jahun": "Jigawa South",
  "jigawa_kafin hausa": "Jigawa South",
  "jigawa_kiyawa": "Jigawa South",
  "jigawa_roni": "Jigawa South",
  "jigawa_sule tankarkar": "Jigawa South",
  "jigawa_taura": "Jigawa South",
  "jigawa_yankwashi": "Jigawa South",

  // Katsina
  "katsina_baure": "Katsina North",
  "katsina_charanchi": "Katsina North",
  "katsina_dan musa": "Katsina North",
  "katsina_daura": "Katsina North",
  "katsina_dutsi": "Katsina North",
  "katsina_ingawa": "Katsina North",
  "katsina_jibia": "Katsina North",
  "katsina_kaita": "Katsina North",
  "katsina_kankara": "Katsina North",
  "katsina_mashi": "Katsina North",
  "katsina_zango": "Katsina North",
  "katsina_bakori": "Katsina Central",
  "katsina_batagarawa": "Katsina Central",
  "katsina_batsari": "Katsina Central",
  "katsina_bindawa": "Katsina Central",
  "katsina_dandume": "Katsina Central",
  "katsina_danja": "Katsina Central",
  "katsina_dutsin ma": "Katsina Central",
  "katsina_kankia": "Katsina Central",
  "katsina_katsina": "Katsina Central",
  "katsina_kurfi": "Katsina Central",
  "katsina_rimi": "Katsina Central",
  "katsina_sandamu": "Katsina Central",
  "katsina_dankama": "Katsina South",
  "katsina_funtua": "Katsina South",
  "katsina_kafur": "Katsina South",
  "katsina_kusada": "Katsina South",
  "katsina_malumfashi": "Katsina South",
  "katsina_matazu": "Katsina South",
  "katsina_musawa": "Katsina South",
  "katsina_sabuwa": "Katsina South",
  "katsina_safana": "Katsina South",

  // Kebbi
  "kebbi_argungu": "Kebbi North",
  "kebbi_arewa dandi": "Kebbi North",
  "kebbi_birnin kebbi": "Kebbi North",
  "kebbi_bunza": "Kebbi North",
  "kebbi_dandi": "Kebbi North",
  "kebbi_gwandu": "Kebbi North",
  "kebbi_jega": "Kebbi North",
  "kebbi_kalgo": "Kebbi North",
  "kebbi_augie": "Kebbi Central",
  "kebbi_bagudo": "Kebbi Central",
  "kebbi_fakai": "Kebbi Central",
  "kebbi_koko/besse": "Kebbi Central",
  "kebbi_maiyama": "Kebbi Central",
  "kebbi_shanga": "Kebbi Central",
  "kebbi_suru": "Kebbi Central",
  "kebbi_yauri": "Kebbi Central",
  "kebbi_zuru": "Kebbi Central",
  "kebbi_lokon": "Kebbi South",
  "kebbi_ngaski": "Kebbi South",
  "kebbi_sakaba": "Kebbi South",
  "kebbi_wasagu/danko": "Kebbi South",

  // Nasarawa
  "nasarawa_akwanga": "Nasarawa North",
  "nasarawa_keffi": "Nasarawa North",
  "nasarawa_kokona": "Nasarawa North",
  "nasarawa_nasarawa": "Nasarawa North",
  "nasarawa_nasarawa egon": "Nasarawa North",
  "nasarawa_wamba": "Nasarawa North",
  "nasarawa_awe": "Nasarawa South",
  "nasarawa_doma": "Nasarawa South",
  "nasarawa_keana": "Nasarawa South",
  "nasarawa_lafia": "Nasarawa South",
  "nasarawa_obi": "Nasarawa South",
  "nasarawa_karu": "Nasarawa West",
  "nasarawa_toto": "Nasarawa West",

  // Niger
  "niger_bosso": "Niger East",
  "niger_chanchaga": "Niger East",
  "niger_gurara": "Niger East",
  "niger_katcha": "Niger East",
  "niger_lapai": "Niger East",
  "niger_lavun": "Niger East",
  "niger_mokwa": "Niger East",
  "niger_paikoro": "Niger East",
  "niger_suleja": "Niger East",
  "niger_tafa": "Niger East",
  "niger_wushishi": "Niger East",
  "niger_agwara": "Niger North",
  "niger_borgu": "Niger North",
  "niger_edati": "Niger North",
  "niger_gbako": "Niger North",
  "niger_kontagora": "Niger North",
  "niger_magama": "Niger North",
  "niger_mariga": "Niger North",
  "niger_mashegu": "Niger North",
  "niger_munya": "Niger North",
  "niger_rafi": "Niger North",
  "niger_rijau": "Niger North",
  "niger_shiroro": "Niger North",
  "niger_agaie": "Niger South",
  "niger_bida": "Niger South",
  "niger_gbako_south": "Niger South",

  // Plateau
  "plateau_bassa": "Plateau North",
  "plateau_bokkos": "Plateau North",
  "plateau_jos east": "Plateau North",
  "plateau_jos north": "Plateau North",
  "plateau_jos south": "Plateau North",
  "plateau_kanam": "Plateau North",
  "plateau_kanke": "Plateau North",
  "plateau_riyom": "Plateau North",
  "plateau_barkin ladi": "Plateau Central",
  "plateau_mangu": "Plateau Central",
  "plateau_mikang": "Plateau Central",
  "plateau_pankshin": "Plateau Central",
  "plateau_langtang north": "Plateau South",
  "plateau_langtang south": "Plateau South",
  "plateau_qua'an pan": "Plateau South",
  "plateau_shendam": "Plateau South",
  "plateau_wase": "Plateau South",

  // Sokoto
  "sokoto_dange shuni": "Sokoto East",
  "sokoto_dange-shuni": "Sokoto East",
  "sokoto_gada": "Sokoto East",
  "sokoto_goronyo": "Sokoto East",
  "sokoto_gudu": "Sokoto East",
  "sokoto_gwadabawa": "Sokoto East",
  "sokoto_illela": "Sokoto East",
  "sokoto_isa": "Sokoto East",
  "sokoto_kware": "Sokoto East",
  "sokoto_rabah": "Sokoto East",
  "sokoto_sabon birni": "Sokoto East",
  "sokoto_silame": "Sokoto East",
  "sokoto_binji": "Sokoto North",
  "sokoto_bodinga": "Sokoto North",
  "sokoto_kebbe": "Sokoto North",
  "sokoto_shagari": "Sokoto North",
  "sokoto_sokoto north lga": "Sokoto North",
  "sokoto_sokoto south lga": "Sokoto North",
  "sokoto_tambuwel": "Sokoto North",
  "sokoto_tangaza": "Sokoto North",
  "sokoto_tureta": "Sokoto North",
  "sokoto_wamako": "Sokoto North",
  "sokoto_wurno": "Sokoto North",
  "sokoto_yabo": "Sokoto North",
  "sokoto_gorori": "Sokoto South",
  "sokoto_kware_south": "Sokoto South",
  "sokoto_rabah_south": "Sokoto South",
  "sokoto_tambuwel_south": "Sokoto South",
  "sokoto_wurno_south": "Sokoto South",

  // Taraba
  "taraba_ardo-kola": "Taraba North",
  "taraba_ardo kola": "Taraba North",
  "taraba_bali": "Taraba North",
  "taraba_donga": "Taraba North",
  "taraba_gashaka": "Taraba North",
  "taraba_gassol": "Taraba North",
  "taraba_ibi": "Taraba North",
  "taraba_jalingo": "Taraba North",
  "taraba_karim lamido": "Taraba North",
  "taraba_kurmi": "Taraba North",
  "taraba_lau": "Taraba Central",
  "taraba_sardauna": "Taraba Central",
  "taraba_takum": "Taraba Central",
  "taraba_ussa": "Taraba Central",
  "taraba_wukari": "Taraba Central",
  "taraba_yorro": "Taraba South",
  "taraba_zing": "Taraba South",

  // Yobe
  "yobe_bade": "Yobe East",
  "yobe_geidam": "Yobe East",
  "yobe_jakusko": "Yobe East",
  "yobe_karasuwa": "Yobe East",
  "yobe_machina": "Yobe East",
  "yobe_nguru": "Yobe East",
  "yobe_potiskum": "Yobe East",
  "yobe_bursari": "Yobe North",
  "yobe_damaturu": "Yobe North",
  "yobe_fune": "Yobe North",
  "yobe_gulani": "Yobe North",
  "yobe_yunusari": "Yobe North",
  "yobe_yusufari": "Yobe North",
  "yobe_fika": "Yobe West",
  "yobe_gujba": "Yobe West",
  "yobe_nangere": "Yobe West",
  "yobe_tarmuwa": "Yobe West",

  // Zamfara
  "zamfara_anka": "Zamfara Central",
  "zamfara_gusau": "Zamfara Central",
  "zamfara_maru": "Zamfara Central",
  "zamfara_tsafe": "Zamfara Central",
  "zamfara_bakura": "Zamfara North",
  "zamfara_bungudu": "Zamfara North",
  "zamfara_kaura namoda": "Zamfara North",
  "zamfara_shinkafi": "Zamfara North",
  "zamfara_zurmi": "Zamfara North",
  "zamfara_birnin magaji/kiyaw": "Zamfara West",
  "zamfara_birnin magaji kiyaw": "Zamfara West",
  "zamfara_bukkuyum": "Zamfara West",
  "zamfara_gummi": "Zamfara West",
  "zamfara_maradun": "Zamfara West",
  "zamfara_talata mafara": "Zamfara West",

  // Abia
  "abia_arochukwu": "Abia North",
  "abia_bende": "Abia North",
  "abia_isuikwuato": "Abia North",
  "abia_ohafia": "Abia North",
  "abia_umu nneochi": "Abia North",
  "abia_umu-nneochi": "Abia North",
  "abia_ikwuano": "Abia Central",
  "abia_isiala ngwa north": "Abia Central",
  "abia_isiala-ngwa-north": "Abia Central",
  "abia_isiala ngwa south": "Abia Central",
  "abia_isiala-ngwa-south": "Abia Central",
  "abia_osisioma ngwa": "Abia Central",
  "abia_osisioma-ngwa": "Abia Central",
  "abia_osisioma": "Abia Central",
  "abia_umuahia north": "Abia Central",
  "abia_umuahia-north": "Abia Central",
  "abia_umuahia south": "Abia Central",
  "abia_umuahia-south": "Abia Central",
  "abia_aba north": "Abia South",
  "abia_aba-north": "Abia South",
  "abia_aba south": "Abia South",
  "abia_aba-south": "Abia South",
  "abia_obi ngwa": "Abia South",
  "abia_obi-ngwa": "Abia South",
  "abia_obingwa": "Abia South",
  "abia_ugwunagbo": "Abia South",
  "abia_ukwa east": "Abia South",
  "abia_ukwa-east": "Abia South",
  "abia_ukwa west": "Abia South",
  "abia_ukwa-west": "Abia South",

  // Akwa Ibom
  "akwa ibom_etinan": "Akwa Ibom North East",
  "akwa ibom_ibesikpo asutan": "Akwa Ibom North East",
  "akwa ibom_ibesikpo-asutan": "Akwa Ibom North East",
  "akwa ibom_ibiono ibom": "Akwa Ibom North East",
  "akwa ibom_ibiono-ibom": "Akwa Ibom North East",
  "akwa ibom_itu": "Akwa Ibom North East",
  "akwa ibom_nsit atai": "Akwa Ibom North East",
  "akwa ibom_nsit-atai": "Akwa Ibom North East",
  "akwa ibom_nsit ibom": "Akwa Ibom North East",
  "akwa ibom_nsit-ibom": "Akwa Ibom North East",
  "akwa ibom_nsit ubium": "Akwa Ibom North East",
  "akwa ibom_nsit-ubium": "Akwa Ibom North East",
  "akwa ibom_uruan": "Akwa Ibom North East",
  "akwa ibom_uyo": "Akwa Ibom North East",
  "akwa ibom_abak": "Akwa Ibom North West",
  "akwa ibom_essien udim": "Akwa Ibom North West",
  "akwa ibom_essien-udim": "Akwa Ibom North West",
  "akwa ibom_etim ekpo": "Akwa Ibom North West",
  "akwa ibom_etim-ekpo": "Akwa Ibom North West",
  "akwa ibom_ika": "Akwa Ibom North West",
  "akwa ibom_ikono": "Akwa Ibom North West",
  "akwa ibom_ikot ekpene": "Akwa Ibom North West",
  "akwa ibom_ikot-ekpene": "Akwa Ibom North West",
  "akwa ibom_ini": "Akwa Ibom North West",
  "akwa ibom_obot akara": "Akwa Ibom North West",
  "akwa ibom_obot-akara": "Akwa Ibom North West",
  "akwa ibom_oruk anam": "Akwa Ibom North West",
  "akwa ibom_oruk-anam": "Akwa Ibom North West",
  "akwa ibom_ukanafun": "Akwa Ibom North West",
  "akwa ibom_eastern obolo": "Akwa Ibom South",
  "akwa ibom_eastern-obolo": "Akwa Ibom South",
  "akwa ibom_eket": "Akwa Ibom South",
  "akwa ibom_esit eket": "Akwa Ibom South",
  "akwa ibom_esit-eket": "Akwa Ibom South",
  "akwa ibom_ibeno": "Akwa Ibom South",
  "akwa ibom_ikot abasi": "Akwa Ibom South",
  "akwa ibom_ikot-abasi": "Akwa Ibom South",
  "akwa ibom_mbo": "Akwa Ibom South",
  "akwa ibom_mkpat enin": "Akwa Ibom South",
  "akwa ibom_mkpat-enin": "Akwa Ibom South",
  "akwa ibom_okobo": "Akwa Ibom South",
  "akwa ibom_onna": "Akwa Ibom South",
  "akwa ibom_oron": "Akwa Ibom South",
  "akwa ibom_udung uko": "Akwa Ibom South",
  "akwa ibom_udung-uko": "Akwa Ibom South",
  "akwa ibom_urue offong/oruko": "Akwa Ibom South",
  "akwa ibom_urue-offong/oruko": "Akwa Ibom South",
  "akwa ibom_urue offong oruko": "Akwa Ibom South",

  // Anambra
  "anambra_anaocha": "Anambra Central",
  "anambra_awka north": "Anambra Central",
  "anambra_awka-north": "Anambra Central",
  "anambra_awka south": "Anambra Central",
  "anambra_awka-south": "Anambra Central",
  "anambra_dunukofia": "Anambra Central",
  "anambra_idemili north": "Anambra Central",
  "anambra_idemili-north": "Anambra Central",
  "anambra_idemili south": "Anambra Central",
  "anambra_idemili-south": "Anambra Central",
  "anambra_njikoka": "Anambra Central",
  "anambra_anambra east": "Anambra North",
  "anambra_anambra-east": "Anambra North",
  "anambra_anambra west": "Anambra North",
  "anambra_anambra-west": "Anambra North",
  "anambra_ayamelum": "Anambra North",
  "anambra_ogbaru": "Anambra North",
  "anambra_onitsha north": "Anambra North",
  "anambra_onitsha-north": "Anambra North",
  "anambra_onitsha south": "Anambra North",
  "anambra_onitsha-south": "Anambra North",
  "anambra_oyi": "Anambra North",
  "anambra_aguata": "Anambra South",
  "anambra_ekwusigo": "Anambra South",
  "anambra_ihiala": "Anambra South",
  "anambra_nnewi north": "Anambra South",
  "anambra_nnewi-north": "Anambra South",
  "anambra_nnewi south": "Anambra South",
  "anambra_nnewi-south": "Anambra South",
  "anambra_orumba north": "Anambra South",
  "anambra_orumba-north": "Anambra South",
  "anambra_orumba south": "Anambra South",
  "anambra_orumba-south": "Anambra South",

  // Bayelsa
  "bayelsa_brass": "Bayelsa East",
  "bayelsa_nembe": "Bayelsa East",
  "bayelsa_ogbia": "Bayelsa East",
  "bayelsa_kolokuma/opokuma": "Bayelsa Central",
  "bayelsa_kolokuma opokuma": "Bayelsa Central",
  "bayelsa_kolokuma-opokuma": "Bayelsa Central",
  "bayelsa_southern ijaw": "Bayelsa Central",
  "bayelsa_southern-ijaw": "Bayelsa Central",
  "bayelsa_yenagoa": "Bayelsa Central",
  "bayelsa_ekeremor": "Bayelsa West",
  "bayelsa_sagbama": "Bayelsa West",

  // Cross River
  "cross river_bekwarra": "Cross River North",
  "cross river_obanliku": "Cross River North",
  "cross river_obudu": "Cross River North",
  "cross river_ogoja": "Cross River North",
  "cross river_yala": "Cross River North",
  "cross river_abi": "Cross River Central",
  "cross river_boki": "Cross River Central",
  "cross river_etung": "Cross River Central",
  "cross river_ikom": "Cross River Central",
  "cross river_obubra": "Cross River Central",
  "cross river_yakurr": "Cross River Central",
  "cross river_akamkpa": "Cross River South",
  "cross river_akpabuyo": "Cross River South",
  "cross river_bakassi": "Cross River South",
  "cross river_biase": "Cross River South",
  "cross river_calabar municipal": "Cross River South",
  "cross river_calabar-municipal": "Cross River South",
  "cross river_calabar south": "Cross River South",
  "cross river_calabar-south": "Cross River South",
  "cross river_odukpani": "Cross River South",

  // Delta
  "delta_ethiope east": "Delta Central",
  "delta_ethiope-east": "Delta Central",
  "delta_ethiope west": "Delta Central",
  "delta_ethiope-west": "Delta Central",
  "delta_okpe": "Delta Central",
  "delta_sapele": "Delta Central",
  "delta_udu": "Delta Central",
  "delta_ughelli north": "Delta Central",
  "delta_ughelli-north": "Delta Central",
  "delta_ughelli south": "Delta Central",
  "delta_ughelli-south": "Delta Central",
  "delta_uvwie": "Delta Central",
  "delta_aniocha north": "Delta North",
  "delta_aniocha-north": "Delta North",
  "delta_aniocha south": "Delta North",
  "delta_aniocha-south": "Delta North",
  "delta_ika north east": "Delta North",
  "delta_ika-north-east": "Delta North",
  "delta_ika south": "Delta North",
  "delta_ika-south": "Delta North",
  "delta_ndokwa east": "Delta North",
  "delta_ndokwa-east": "Delta North",
  "delta_ndokwa west": "Delta North",
  "delta_ndokwa-west": "Delta North",
  "delta_oshimili north": "Delta North",
  "delta_oshimili-north": "Delta North",
  "delta_oshimili south": "Delta North",
  "delta_oshimili-south": "Delta North",
  "delta_ukwuani": "Delta North",
  "delta_bomadi": "Delta South",
  "delta_burutu": "Delta South",
  "delta_isoko north": "Delta South",
  "delta_isoko-north": "Delta South",
  "delta_isoko south": "Delta South",
  "delta_isoko-south": "Delta South",
  "delta_patani": "Delta South",
  "delta_warri north": "Delta South",
  "delta_warri-north": "Delta South",
  "delta_warri south": "Delta South",
  "delta_warri-south": "Delta South",
  "delta_warri south west": "Delta South",
  "delta_warri-south-west": "Delta South",

  // Ebonyi
  "ebonyi_abakaliki": "Ebonyi North",
  "ebonyi_ebonyi": "Ebonyi North",
  "ebonyi_izzi": "Ebonyi North",
  "ebonyi_ohaukwu": "Ebonyi North",
  "ebonyi_ezza north": "Ebonyi Central",
  "ebonyi_ezza-north": "Ebonyi Central",
  "ebonyi_ezza south": "Ebonyi Central",
  "ebonyi_ezza-south": "Ebonyi Central",
  "ebonyi_ikwo": "Ebonyi Central",
  "ebonyi_ishielu": "Ebonyi Central",
  "ebonyi_afikpo north": "Ebonyi South",
  "ebonyi_afikpo-north": "Ebonyi South",
  "ebonyi_afikpo south": "Ebonyi South",
  "ebonyi_afikpo-south": "Ebonyi South",
  "ebonyi_edda": "Ebonyi South",
  "ebonyi_ivo": "Ebonyi South",
  "ebonyi_ohaozara": "Ebonyi South",
  "ebonyi_onicha": "Ebonyi South",

  // Ekiti
  "ekiti_ado-ekiti": "Ekiti Central",
  "ekiti_ado ekiti": "Ekiti Central",
  "ekiti_efon": "Ekiti Central",
  "ekiti_ekiti west": "Ekiti Central",
  "ekiti_ekiti-west": "Ekiti Central",
  "ekiti_ijero": "Ekiti Central",
  "ekiti_irepodun/ifelodun": "Ekiti Central",
  "ekiti_irepodun ifelodun": "Ekiti Central",
  "ekiti_ido-osi": "Ekiti North",
  "ekiti_ido osi": "Ekiti North",
  "ekiti_ilejemeje": "Ekiti North",
  "ekiti_ikole": "Ekiti North",
  "ekiti_moba": "Ekiti North",
  "ekiti_oye": "Ekiti North",
  "ekiti_ekiti east": "Ekiti South",
  "ekiti_ekiti-east": "Ekiti South",
  "ekiti_ekiti south-west": "Ekiti South",
  "ekiti_ekiti south west": "Ekiti South",
  "ekiti_ekiti-south-west": "Ekiti South",
  "ekiti_emure": "Ekiti South",
  "ekiti_gbonyin": "Ekiti South",
  "ekiti_ikere": "Ekiti South",
  "ekiti_ise/orun": "Ekiti South",
  "ekiti_ise orun": "Ekiti South",

  // Enugu
  "enugu_enugu east": "Enugu East",
  "enugu_enugu-east": "Enugu East",
  "enugu_enugu north": "Enugu East",
  "enugu_enugu-north": "Enugu East",
  "enugu_enugu south": "Enugu East",
  "enugu_enugu-south": "Enugu East",
  "enugu_isi-uzo": "Enugu East",
  "enugu_isi uzo": "Enugu East",
  "enugu_nkanu east": "Enugu East",
  "enugu_nkanu-east": "Enugu East",
  "enugu_nkanu west": "Enugu East",
  "enugu_nkanu-west": "Enugu East",
  "enugu_igbo-etiti": "Enugu North",
  "enugu_igbo etiti": "Enugu North",
  "enugu_igbo-eze north": "Enugu North",
  "enugu_igbo eze north": "Enugu North",
  "enugu_igbo-eze south": "Enugu North",
  "enugu_igbo eze south": "Enugu North",
  "enugu_nsukka": "Enugu North",
  "enugu_udenu": "Enugu North",
  "enugu_uzo-uwani": "Enugu North",
  "enugu_uzo uwani": "Enugu North",
  "enugu_aninri": "Enugu West",
  "enugu_awgu": "Enugu West",
  "enugu_ezeagu": "Enugu West",
  "enugu_oji-river": "Enugu West",
  "enugu_oji river": "Enugu West",
  "enugu_udi": "Enugu West",

  // Imo
  "imo_ideato north": "Imo West",
  "imo_ideato-north": "Imo West",
  "imo_ideato south": "Imo West",
  "imo_ideato-south": "Imo West",
  "imo_isu": "Imo West",
  "imo_njaba": "Imo West",
  "imo_nkwerre": "Imo West",
  "imo_nwangele": "Imo West",
  "imo_oguta": "Imo West",
  "imo_ohaji/egbema": "Imo West",
  "imo_ohaji egbema": "Imo West",
  "imo_orlu": "Imo West",
  "imo_orsu": "Imo West",
  "imo_oru east": "Imo West",
  "imo_oru-east": "Imo West",
  "imo_oru west": "Imo West",
  "imo_oru-west": "Imo West",
  "imo_aboh mbaise": "Imo East",
  "imo_aboh-mbaise": "Imo East",
  "imo_ahiazu mbaise": "Imo East",
  "imo_ahiazu-mbaise": "Imo East",
  "imo_ezinihitte": "Imo East",
  "imo_ezinihitte mbaise": "Imo East",
  "imo_ikeduru": "Imo East",
  "imo_mbaitoli": "Imo East",
  "imo_ngor okpala": "Imo East",
  "imo_ngor-okpala": "Imo East",
  "imo_owerri municipal": "Imo East",
  "imo_owerri north": "Imo East",
  "imo_owerri-north": "Imo East",
  "imo_owerri west": "Imo East",
  "imo_owerri-west": "Imo East",
  "imo_ehime mbano": "Imo North",
  "imo_ehime-mbano": "Imo North",
  "imo_ihitte/uboma": "Imo North",
  "imo_ihitte uboma": "Imo North",
  "imo_ihitte-uboma": "Imo North",
  "imo_isiala mbano": "Imo North",
  "imo_isiala-mbano": "Imo North",
  "imo_obowo": "Imo North",
  "imo_okigwe": "Imo North",
  "imo_onuimo": "Imo North",

  // Kogi
  "kogi_adavi": "Kogi Central",
  "kogi_ajaokuta": "Kogi Central",
  "kogi_okehi": "Kogi Central",
  "kogi_okene": "Kogi Central",
  "kogi_ogori-magongo": "Kogi Central",
  "kogi_ogori magongo": "Kogi Central",
  "kogi_ankpa": "Kogi East",
  "kogi_bassa": "Kogi East",
  "kogi_dekina": "Kogi East",
  "kogi_ibaji": "Kogi East",
  "kogi_idah": "Kogi East",
  "kogi_igalamela-odolu": "Kogi East",
  "kogi_igalamela odolu": "Kogi East",
  "kogi_ofu": "Kogi East",
  "kogi_olamaboro": "Kogi East",
  "kogi_omala": "Kogi East",
  "kogi_ijumu": "Kogi West",
  "kogi_kabba/bunu": "Kogi West",
  "kogi_kabba bunu": "Kogi West",
  "kogi_kogi": "Kogi West",
  "kogi_koton karfe": "Kogi West",
  "kogi_koton-karfe": "Kogi West",
  "kogi_lokoja": "Kogi West",
  "kogi_mopa-muro": "Kogi West",
  "kogi_mopa muro": "Kogi West",
  "kogi_yagba east": "Kogi West",
  "kogi_yagba-east": "Kogi West",
  "kogi_yagba west": "Kogi West",
  "kogi_yagba-west": "Kogi West",

  // Lagos
  "lagos_apapa": "Lagos Central",
  "lagos_eti-osa": "Lagos Central",
  "lagos_eti osa": "Lagos Central",
  "lagos_lagos island": "Lagos Central",
  "lagos_lagos-island": "Lagos Central",
  "lagos_lagos mainland": "Lagos Central",
  "lagos_lagos-mainland": "Lagos Central",
  "lagos_surulere": "Lagos Central",
  "lagos_agege": "Lagos West",
  "lagos_ajeromi-ifelodun": "Lagos West",
  "lagos_ajeromi ifelodun": "Lagos West",
  "lagos_alimosho": "Lagos West",
  "lagos_amuwo-odofin": "Lagos West",
  "lagos_amuwo odofin": "Lagos West",
  "lagos_badagry": "Lagos West",
  "lagos_ifako-ijaiye": "Lagos West",
  "lagos_ifako ijaiye": "Lagos West",
  "lagos_ikeja": "Lagos West",
  "lagos_mushin": "Lagos West",
  "lagos_ojo": "Lagos West",
  "lagos_oshodi-isolo": "Lagos West",
  "lagos_oshodi isolo": "Lagos West",
  "lagos_epe": "Lagos East",
  "lagos_ibeju-lekki": "Lagos East",
  "lagos_ibeju lekki": "Lagos East",
  "lagos_ikorodu": "Lagos East",
  "lagos_kosofe": "Lagos East",
  "lagos_somolu": "Lagos East",
  "lagos_shomolu": "Lagos East",

  // Osun
  "osun_boluwaduro": "Osun Central",
  "osun_boripe": "Osun Central",
  "osun_ifedayo": "Osun Central",
  "osun_ifelodun": "Osun Central",
  "osun_ila": "Osun Central",
  "osun_irepodun": "Osun Central",
  "osun_odo otin": "Osun Central",
  "osun_odo-otin": "Osun Central",
  "osun_olorunda": "Osun Central",
  "osun_orolu": "Osun Central",
  "osun_osogbo": "Osun Central",
  "osun_atakumosa east": "Osun East",
  "osun_atakumosa-east": "Osun East",
  "osun_atakumosa west": "Osun East",
  "osun_atakumosa-west": "Osun East",
  "osun_ife central": "Osun East",
  "osun_ife-central": "Osun East",
  "osun_ife east": "Osun East",
  "osun_ife-east": "Osun East",
  "osun_ife north": "Osun East",
  "osun_ife-north": "Osun East",
  "osun_ife south": "Osun East",
  "osun_ife-south": "Osun East",
  "osun_ilesa east": "Osun East",
  "osun_ilesa-east": "Osun East",
  "osun_ilesa west": "Osun East",
  "osun_ilesa-west": "Osun East",
  "osun_obokun": "Osun East",
  "osun_oriade": "Osun East",
  "osun_ayedaade": "Osun West",
  "osun_ayedaade_west": "Osun West",
  "osun_ayedire": "Osun West",
  "osun_ede north": "Osun West",
  "osun_ede-north": "Osun West",
  "osun_ede south": "Osun West",
  "osun_ede-south": "Osun West",
  "osun_egbedore": "Osun West",
  "osun_ejigbo": "Osun West",
  "osun_irewole": "Osun West",
  "osun_isokan": "Osun West",
  "osun_iwo": "Osun West",
  "osun_ola oluwa": "Osun West",
  "osun_ola-oluwa": "Osun West",

  // Rivers
  "rivers_emohua": "Rivers East",
  "rivers_etche": "Rivers East",
  "rivers_ikwerre": "Rivers East",
  "rivers_obio-akpor": "Rivers East",
  "rivers_obio akpor": "Rivers East",
  "rivers_ogu-bolo": "Rivers East",
  "rivers_ogu bolo": "Rivers East",
  "rivers_okrika": "Rivers East",
  "rivers_omuma": "Rivers East",
  "rivers_port harcourt": "Rivers East",
  "rivers_port-harcourt": "Rivers East",
  "rivers_andoni": "Rivers South East",
  "rivers_eleme": "Rivers South East",
  "rivers_gokana": "Rivers South East",
  "rivers_khana": "Rivers South East",
  "rivers_opobo-nkoro": "Rivers South East",
  "rivers_opobo nkoro": "Rivers South East",
  "rivers_oyigbo": "Rivers South East",
  "rivers_tai": "Rivers South East",
  "rivers_abua-odual": "Rivers West",
  "rivers_abua odual": "Rivers West",
  "rivers_ahoada east": "Rivers West",
  "rivers_ahoada-east": "Rivers West",
  "rivers_ahoada west": "Rivers West",
  "rivers_ahoada-west": "Rivers West",
  "rivers_akuku-toru": "Rivers West",
  "rivers_akuku toru": "Rivers West",
  "rivers_asari-toru": "Rivers West",
  "rivers_asari toru": "Rivers West",
  "rivers_bonny": "Rivers West",
  "rivers_degema": "Rivers West",
  "rivers_ogba-egbema-ndoni": "Rivers West",
  "rivers_ogba egbema ndoni": "Rivers West",
};

export const normalizeStateForZone = (stateStr: string): string => {
  if (!stateStr) return "";
  let s = stateStr.toLowerCase();
  if (s.includes("abuja") || s.includes("fct")) return "abuja (fct)";
  s = s.replace(/\s*state/gi, "").trim();
  return s;
};

export const getSenatorialZone = (stateName: string, lgaName: string): string => {
  if (!stateName || !lgaName) return "";
  const normState = normalizeStateForZone(stateName);
  const normLga = lgaName.trim().toLowerCase();

  // Try direct lookup
  const directKey = `${normState}_${normLga}`;
  if (LGA_ZONE_MAP[directKey]) {
    return LGA_ZONE_MAP[directKey];
  }

  // Fallback cleanup match (ignoring spaces/hyphens)
  const cleanedLga = normLga.replace(/[-\s]/g, "");
  const matchKey = Object.keys(LGA_ZONE_MAP).find((key) => {
    const [st, lg] = key.split("_");
    if (st !== normState) return false;
    const cleanedKeyLga = lg.replace(/[-\s]/g, "");
    return (
      cleanedKeyLga === cleanedLga ||
      cleanedKeyLga.includes(cleanedLga) ||
      cleanedLga.includes(cleanedKeyLga)
    );
  });

  if (matchKey) {
    return LGA_ZONE_MAP[matchKey];
  }

  return "";
};
